spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

logging:
  level:
    root: info